version: '3.8'

services:


  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-db
    environment:

      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenhaForte#123 
    ports:
 
      - "1433:1433"
    volumes:

      - mssql-data:/var/opt/mssql

  api:

    build: .
    container_name: fcg-api-dev
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

      - ConnectionStrings__DefaultConnection=Server=db;Database=FiapCloudGames;User Id=sa;Password=SuaSenhaForte#123;TrustServerCertificate=True;
    depends_on:
      - db

volumes:
  mssql-data: